version: "3.8"
services:
  proxy:
    build:
      context: .
      dockerfile: ./docker/proxy/Dockerfile.proxy
      target: prod
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - nginx
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile.vue
      target: prod
    container_name: frontend
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile.laravel
    container_name: api
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
      - redis

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile.mysql
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redisdata:/data

  inicialization:
    build:
      context: .
      dockerfile: ./docker/inicialization/Dockerfile
    container_name: inicialization
    restart: no
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DB_USER: backend
      DB_PASSWORD: password
      MAX_WAIT: 120
      WAIT_INTERVAL: 10
      MYSQL_CONTAINER_NAME: mysql
      API_CONTAINER_NAME: api
      mode: prod
    depends_on:
      - mysql
      - redis
      - api